language: python
python:
 - 2.6
 - 2.7
 - 3.2
 - 3.3
install:
 - python setup.py develop
 - pip install nose webtest coveralls
 # Install unittest2 on 2.6
 - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi"
script: python setup.py nosetests --config nose_cover.cfg
after_success: coveralls
