language: python
python:
 - 2.7
 - 3.3
 - 3.4
install:
 - python setup.py develop
 - pip install pytest pytest-cov webtest coveralls
script: py.test --cov pyramid_skosprovider --cov-report term-missing
after_success: coveralls
